### ISSUE TITLE
Crash during a server launch!

### ISSUE THREAD

**Issue by Samlegamer** [JMilamber/Brass_Amber_BattleTowers#51]
When launching the server in forge-2.20-1.16.5 it stops.

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 30/12/21 23:12
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge.jar:36.2] {}
-- MOD ba_bt --
Details:
	Mod File: BrassAmberBattleTowers-1.16.5-1.1.3.jar
	Failure message: Brass Amber BattleTowers (ba_bt) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
	Mod Version: 1.16.5-1.1.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_311] {}
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:256) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:78) ~[eventbus-4.0.0.jar:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:78) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_311] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3735504752 bytes (3562 MB) / 4239392768 bytes (4043 MB) up to 4239392768 bytes (4043 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.16.0
	Mod List: 
		FriendlyEndermite_v1.0.3_mc1.16.5.jar             |Friendly Endermite            |friendlyendermite             |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		GlobalGameRules-1.16.5-5.1.0.4.jar                |Global GameRules              |globalgamerules               |5.1.0.4             |CREATE_REG|Manifest: 15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		foodexpansion-1.6.1.jar                           |Food Expansion: Reimagined    |foodexpansion                 |1.6.1               |CREATE_REG|Manifest: NOSIGNATURE
		UnionLib-1.16.5-3.3.7.jar                         |UnionLib                      |unionlib                      |3.3.7               |CREATE_REG|Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |CREATE_REG|Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.2.2.0-build.0202.jar      |Forge Endertech               |forgeendertech                |7.2.2.0             |CREATE_REG|Manifest: NOSIGNATURE
		diamondNuggets-forge-1.3-1.16.4+5.jar             |Diamond Nuggets               |diamond_nuggets               |1.3                 |CREATE_REG|Manifest: NOSIGNATURE
		EnhancedVisuals_v1.3.32_mc1.16.5.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |CREATE_REG|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.16.5-3.14.3.484.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.14.3.484   |CREATE_REG|Manifest: NOSIGNATURE
		SnowRealMagic-1.16.4-2.8.3.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.8.3               |CREATE_REG|Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.22.jar                      |Carry On                      |carryon                       |1.15.5.22           |CREATE_REG|Manifest: NOSIGNATURE
		konkrete_forge_1.3.2_MC_1.16.2-1.16.5.jar         |Konkrete                      |konkrete                      |1.3.2               |CREATE_REG|Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |CREATE_REG|Manifest: NOSIGNATURE
		AmbientSounds_v3.1.11_mc1.16.5.jar                |Ambient Sounds                |ambientsounds                 |3.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		AIReducer-1.16-0.1.0.jar                          |AI Reducer                    |aireducer                     |0.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		CraftableChainmailReborn-1.16.5-1.0.jar           |Craftable Chainmail Reborn    |craftablechainmail            |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |CREATE_REG|Manifest: NOSIGNATURE
		droptherock-1.1.jar                               |Drop the Rock                 |droptherock                   |1.1                 |CREATE_REG|Manifest: NOSIGNATURE
		dungeons_enhanced-1.16.5-1.4.jar                  |Dungeons Enhanced             |dungeons_enhanced             |1.4                 |CREATE_REG|Manifest: NOSIGNATURE
		corpsecomplex-forge-1.16.5-4.0.2.6.jar            |Corpse Complex                |corpsecomplex                 |1.16.5-4.0.2.6      |CREATE_REG|Manifest: NOSIGNATURE
		lycanitesmobs-1.16.5-2.3.3.3.jar                  |Lycanites Mobs                |lycanitesmobs                 |1.16.5-2.3.3.3      |CREATE_REG|Manifest: NOSIGNATURE
		playerex-1.1.8-1.16.5.jar                         |Player Ex                     |playerex                      |1.1.8               |CREATE_REG|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |CREATE_REG|Manifest: NOSIGNATURE
		collective-1.16.5-3.8.jar                         |Collective                    |collective                    |3.8                 |CREATE_REG|Manifest: NOSIGNATURE
		lostcities-1.16-4.0.10-beta.jar                   |LostCities                    |lostcities                    |1.16-4.0.10-beta    |CREATE_REG|Manifest: NOSIGNATURE
		Survive-1.16.5-3.4.6.jar                          |Survive                       |survive                       |1.16.5-3.4.6        |CREATE_REG|Manifest: NOSIGNATURE
		carrotslib-mc1.16.5-3.0b5.jar                     |Carrots Lib                   |carrots                       |3.0b5               |CREATE_REG|Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |CREATE_REG|Manifest: NOSIGNATURE
		antiquewaystones-1.3.jar                          |Antique Waystones             |antiquewaystones              |1.3                 |CREATE_REG|Manifest: NOSIGNATURE
		NetherAgriculture-1.16.5-1.2.1.jar                |Nether Agriculture            |netheragriculture             |1.2.1               |CREATE_REG|Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |CREATE_REG|Manifest: NOSIGNATURE
		AgeingSpawners-1.16.5-1.1.0.jar                   |Ageing Spawners               |ageingspawners                |1.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		ItemPhysic_v1.4.18_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		cloth-config-4.13.49-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.13.49             |CREATE_REG|Manifest: NOSIGNATURE
		enchantwithmob-1.16.5-1.5.2.jar                   |Enchant With Mob              |enchantwithmob                |1.16.5-1.5.2        |CREATE_REG|Manifest: NOSIGNATURE
		switchbow-1.7.jar                                 |Switch-Bow                    |switchbow                     |1.7                 |CREATE_REG|Manifest: NOSIGNATURE
		ScalingHealth-1.16.5-4.0.5+5.jar                  |Scaling Health                |scalinghealth                 |4.0.5+5             |CREATE_REG|Manifest: NOSIGNATURE
		Disenchanting-forge-1.16.5-1.7.2.jar              |Disenchanting                 |disenchanting                 |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta26.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta26|CREATE_REG|Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta10 |CREATE_REG|Manifest: NOSIGNATURE
		so_many_enchants-0.3.0.jar                        |So Many Enchants!!!           |so_many_enchants              |§4§lBETA §60.3.0    |CREATE_REG|Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.6.1.jar                             |Kiwi                          |kiwi                          |3.6.1               |CREATE_REG|Manifest: NOSIGNATURE
		Ma-Enchants-1.16.5-3.6.1.jar                      |Ma Enchants                   |ma-enchants                   |1.16.5-3.6.1        |CREATE_REG|Manifest: NOSIGNATURE
		XPFromHarvest-1.16.3-1.2.1.jar                    |XP From Harvest               |xpfromharvest                 |1.2.1               |CREATE_REG|Manifest: NOSIGNATURE
		Bountiful Baubles FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		locks-1.16.5-3.0.3.jar                            |Locks                         |locks                         |3.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.138.jar                          |Just Enough Items             |jei                           |7.7.1.138           |CREATE_REG|Manifest: NOSIGNATURE
		callablehorses-1.16.3-1.2.1.4.jar                 |Callable Horses               |callablehorses                |1.2.1.4             |CREATE_REG|Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		Paxi-Forge-1.16.4-1.0.jar                         |Paxi                          |paxi                          |1.16.4-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |CREATE_REG|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |CREATE_REG|Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.3.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.3      |CREATE_REG|Manifest: NOSIGNATURE
		tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |CREATE_REG|Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.122-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.122    |CREATE_REG|Manifest: NOSIGNATURE
		configured-1.5.1-1.16.5.jar                       |Configured                    |configured                    |1.5.1               |CREATE_REG|Manifest: NOSIGNATURE
		netheritehorsearmor-1.7.jar                       |Netherite Horse Armor Mod     |netheritehorsearmor           |1.7                 |CREATE_REG|Manifest: NOSIGNATURE
		AdHooks-1.16.5-6.1.8.0-build.0184.jar             |Advanced Hook Launchers       |adhooks                       |6.1.8.0             |CREATE_REG|Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.5.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.5               |CREATE_REG|Manifest: NOSIGNATURE
		wolveswitharmor-1.1.0-1.16.2.jar                  |Wolves With Armor             |wolveswitharmor               |1.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		RealisticTorches-1.16.5-3.1.2.jar                 |Realistic Torches             |realistictorches              |1.16.5-3.1.2        |CREATE_REG|Manifest: NOSIGNATURE
		sulfuric-1.1.jar                                  |Sulfuric                      |sulfuric                      |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		rereskillable-1.16.5-1.3.6.jar                    |Rereskillable                 |rereskillable                 |1.3.6               |CREATE_REG|Manifest: NOSIGNATURE
		traverse-1.16.4-0.4.3.8.jar                       |Traverse: Reforged            |traverse                      |1.16.4-0.4.3.8      |CREATE_REG|Manifest: NOSIGNATURE
		DynamicTreesTraverse-1.16.5-2.2.2.jar             |Dynamic Trees for Traverse    |dttraverse                    |1.16.5-2.2.2        |CREATE_REG|Manifest: NOSIGNATURE
		potionring-1.16.5-1.1.jar                         |Potion Ring                   |potionring                    |1.16.5-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.366.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.366           |CREATE_REG|Manifest: NOSIGNATURE
		firstaid-1.9.7.jar                                |First Aid                     |firstaid                      |1.9.7               |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		notreepunching-forge-1.16.5-4.2.3.jar             |No Tree Punching              |notreepunching                |4.2.3               |CREATE_REG|Manifest: NOSIGNATURE
		meetyourfight-1.16.5-1.2.0.jar                    |Meet Your Fight               |meetyourfight                 |1.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |CREATE_REG|Manifest: NOSIGNATURE
		infernalmobs-1.16.2.1.jar                         |Infernal Mobs                 |infernalmobs                  |1.16.2.1            |CREATE_REG|Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		BrassAmberBattleTowers-1.16.5-1.1.3.jar           |Brass Amber BattleTowers      |ba_bt                         |1.16.5-1.1.3        |ERROR     |Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.18.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.18              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |CREATE_REG|Manifest: NOSIGNATURE
		roughtweaks-1.16.5-2.5.0.jar                      |Rough Tweaks                  |roughtweaks                   |2.5.0               |CREATE_REG|Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|Manifest: NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |CREATE_REG|Manifest: NOSIGNATURE
		silent-lib-1.16.3-4.9.6.jar                       |Silent Lib                    |silentlib                     |4.9.6               |CREATE_REG|Manifest: NOSIGNATURE
		ShoulderSurfing-1.16.5-2.2.1.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.5-2.2.1        |CREATE_REG|Manifest: NOSIGNATURE
		modifiers-0.1.2-forge.jar                         |Modifiers                     |modifiers                     |0.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		armorunder-mc1.16.5-2.0b11.jar                    |Armor Underwear               |armorunder                    |2.0b11              |CREATE_REG|Manifest: NOSIGNATURE
		paintings-1.16.4-7.0.0.1.jar                      |Paintings ++                  |paintings                     |1.16.4-6.0.1.5      |CREATE_REG|Manifest: NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.152.jar                         |Mantle                        |mantle                        |1.6.152             |CREATE_REG|Manifest: NOSIGNATURE
		Inspirations-1.16.5-1.2.3.38.jar                  |Inspirations                  |inspirations                  |1.2.3.38            |CREATE_REG|Manifest: NOSIGNATURE
		serverconfigupdater-1.3.jar                       |ServerConfig Updater          |serverconfigupdater           |1.3                 |CREATE_REG|Manifest: NOSIGNATURE
		sit-1.16.5-v1.3.1.jar                             |Sit                           |sit                           |v1.3.1              |CREATE_REG|Manifest: NOSIGNATURE
		antiquedragons-1.16.5-1.0.jar                     |Antique Dragons               |antiquedragons                |1.16.5-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.0               |CREATE_REG|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		enhancedcelestials-2.0.9-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.9-1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |CREATE_REG|Manifest: NOSIGNATURE
		Craftable Horse Armour  Saddle-1.16.5-1.7--Forge.j|CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.7                 |CREATE_REG|Manifest: NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |CREATE_REG|Manifest: NOSIGNATURE
		xptome-1.16.5-v2.1.2.jar                          |XP Tome                       |xpbook                        |v2.1.2              |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: 44a02040-6ec5-46e8-85f5-4c507d2c91b5
```

**Comment by JMilamber** [comment]
Thank you Sam! I'll have a look tonight  👀.

**Comment by Samlegamer** [comment]
I think I've identified the probable cause of the crash, it would come from the Tile Entities Renderer like the [BTMobSpawnerTileEntityRenderer](https://github.com/JMilamber/Brass_Amber_BattleTowers/blob/main/src/main/java/com/BrassAmber/ba_bt/block/tileentity/client/renderer/BTMobSpawnerTileEntityRenderer.java) which has no `@OnlyIn(Dist.CLIENT)`
I would also advise to add one to the [BTTileEntityRenderInit](https://github.com/JMilamber/Brass_Amber_BattleTowers/blob/main/src/main/java/com/BrassAmber/ba_bt/block/tileentity/client/BTTileEntityRenderInit.java) class or register them in [doClientStuff](https://github.com/JMilamber/Brass_Amber_BattleTowers/blob/main/src/main/java/com/BrassAmber/ba_bt/BrassAmberBattleTowers.java#L201) directly.

**Comment by JMilamber** [comment]
> I think I've identified the probable cause of the crash, it would come from the Tile Entities Renderer like the [BTMobSpawnerTileEntityRenderer](https://github.com/JMilamber/Brass_Amber_BattleTowers/blob/main/src/main/java/com/BrassAmber/ba_bt/block/tileentity/client/renderer/BTMobSpawnerTileEntityRenderer.java) which has no `@OnlyIn(Dist.CLIENT)` I would also advise to add one to the [BTTileEntityRenderInit](https://github.com/JMilamber/Brass_Amber_BattleTowers/blob/main/src/main/java/com/BrassAmber/ba_bt/block/tileentity/client/BTTileEntityRenderInit.java) class or register them in [doClientStuff](https://github.com/JMilamber/Brass_Amber_BattleTowers/blob/main/src/main/java/com/BrassAmber/ba_bt/BrassAmberBattleTowers.java#L201) directly.

Yeah, it was the entity renderers and a few other things, I almost have this fixed locally, should have a commit/pull request up tonight or tomorrow where you can see al of the edits.

**Comment by JMilamber** [comment]
@Samlegamer fix for this is up in Crash-Fix branch.
