### ISSUE TITLE
Server crash when entering tower

### ISSUE THREAD

**Issue by Wehrmicel** [JMilamber/Brass_Amber_BattleTowers#87]
**Describe the bug**
As soon as I walked in the 1rst floor, the server crashed and I am unable to log in anymore without crashing the server.

**To Reproduce**
Things needed to reproduce the behavior:
1. Minecraft Version **1.18.1 & Forge 39.0.79**
2. The version of the mod you are using: **1.18.1-2.0.2**
3. If you are using any datapacks/self-created loot-tables etc: **NO**
4. Server or Singleplayer: **MULTIPLAYER**
5. OS: Windows 10

**Expected behavior**
Being able to explore the tower

**Console log**

[11:58:26] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(net.minecraft.world.entity.Mob, net.minecraft.world.level.LevelAccessor, float, float, float, net.minecraft.world.level.BaseSpawner, net.minecraft.world.entity.MobSpawnType)'
        at com.BrassAmber.ba_bt.block.tileentity.BTBaseSpawner.m_151311_(BTBaseSpawner.java:82) ~[BrassAmberBattleTowers-1.18.1-2.0.2.jar%2344!/:1.18.1-2.0.2]
        at com.BrassAmber.ba_bt.block.tileentity.BTSpawnerBlockEntity.serverTick(BTSpawnerBlockEntity.java:56) ~[BrassAmberBattleTowers-1.18.1-2.0.2.jar%2344!/:1.18.1-2.0.2]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2378!/:?]
        ... 5 more

**Comment by JMilamber** [comment]
Could you try updateing to the most recent forge version for 1.18.1? There was a fix they made for some spawner related stuff, (which this is) that might fix it. 

that would be 39.1.2 -

**Comment by Wehrmicel** [comment]
thank you it worked ! Sorry I haven't tried this earlier.

**Comment by JMilamber** [comment]
No worries! Glad it worked :)

**Comment by RapidCamel** [comment]
Hey there,
I am having the same issue, even though I followed your advice on updating forge.

    Minecraft Version 1.18.1 & Forge 39.1.2
    The version of the mod you are using: 1.18.1-2.0.2
    If you are using any datapacks/self-created loot-tables etc: NO
    Server or Singleplayer: MULTIPLAYER
    OS: Windows 10

Any help would be much appreciated :)

**Crash Log**
Thread: Server thread
Stacktrace:
	at com.BrassAmber.ba_bt.block.tileentity.BTBaseSpawner.m_151311_(BTBaseSpawner.java:82) ~[BrassAmberBattleTowers-1.18.1-2.0.2.jar%2342!/:1.18.1-2.0.2] {re:classloading}
	at com.BrassAmber.ba_bt.block.tileentity.BTSpawnerBlockEntity.serverTick(BTSpawnerBlockEntity.java:56) ~[BrassAmberBattleTowers-1.18.1-2.0.2.jar%2342!/:1.18.1-2.0.2] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading,pl:accesstransformer:B}
-- Block entity being ticked --
Details:
	Name: ba_bt:bt_spawner // com.BrassAmber.ba_bt.block.tileentity.BTSpawnerBlockEntity
	Block: Block{ba_bt:bt_land_spawner}
	Block location: World: (-891,87,111), Section: (at 5,7,15 in -56,5,6; chunk contains blocks -896,-64,96 to -881,319,111), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Block: Block{ba_bt:bt_land_spawner}
	Block location: World: (-891,87,111), Section: (at 5,7,15 in -56,5,6; chunk contains blocks -896,-64,96 to -881,319,111), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by RapidCamel** [comment]
Right on crashing it also mentioned something about Hexxit.jar not found, Forge.jar not found and TekkitLite.jar not found.
I cannot seem to find it in the log anymore though.

**Comment by JMilamber** [comment]
@RapidCamel 

Hey! Appreciate you looking through the closed issues first and trying this fix! 

2 questions:

What Minecraft launcher are you using? 
And is this part of a modpack?

**Comment by RapidCamel** [comment]
Hey JMilabmber,
thank you for your fast reply. I was not sure if that is the right way, commenting on a closed issue.
I checked the crashlog again and realized, I did not properly update forge. 

reinstalled forge and now it works! Thank you again and sorry for the inconvenience.

Updating forge definitely solves this issue.

**Comment by JMilamber** [comment]
No worries! Glad that is the fix :).
